---
title: "Causal Emotions"
author: "Mansi Saxena, Bhaskar Ray"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(igraph)
library(dagitty)
library(lavaan)
library(tidyverse)
library(tidyr)
library(dplyr)
library(nnet)
library(emmeans)
library(readr)       # For read_delim
library(openxlsx)    # For Excel writing

rm(list=ls())
```

```{r setup_functions}
append_to_csv <- function(new_row) {
  # Check if the Excel file already exists
  if (file.exists("Causal_Binary.csv")) {
    data <- read_delim("Causal_Binary.csv", delim = "|", col_names = TRUE)
    data <- bind_rows(data, new_row)
    write_delim(data, "Causal_Binary.csv", delim = "|", append = F)
  } else {
    # If the file doesn't exist, create a new Excel file with the data
    data <- new_row
    write_delim(data, "Causal_Binary.csv", delim = "|", append = F)
  }
}
```

```{r DAG_specification}
# dag_df <- read.csv("Violence Analysis Project - DAG_new.csv")
# 
# dag_df[is.na(dag_df)] <- 0
# 
# vars <- gsub("\\.", "", colnames(dag_df)[-1])
# 
# sink(file = "D:\\Academics\\Degree Programs\\PhD\\Emotion Analysis\\Data\\DAG_new.txt")
# for(i in 1:nrow(dag_df))
# {
#   for(j in 1:nrow(dag_df))
#   {
#     if(dag_df[i, j] == 1)
#       cat(vars[i], " -> ", vars[j], "\n", sep = "")
#   }
# }
# sink()
```

```{r DAG}

library(dagitty)

mydag <- dagitty('dag {
  bb="-7.581,-8.712,6.036,7.797"
  IntimatePartner
  FamilyMember
  CloseFriend
  Colleague
  AuthorityFigure
  Stranger
  Domestic 
  Professional 
  Public
  Social
  Cyber
  NightTime
  Intoxication
  Singular
  Recurring
  NotEndingAbuse
  EnablingAbuser
  Abuser
  Supporters
  Antagonists
  Physical
  Verbal
  Economic
  Technological 
  SexualHarassment
  SexualAssault
  ConfrontingAbuser
  Reporting
  SeveringTies
  SeekingLegalClassification
  SeekingLegalAdvice
  SeekingGeneralSupport
  Nightmares
  Injury
  FinancialInstability
  LegalBarriers
  SelfHarming

  IntimatePartner -> Domestic
  IntimatePartner -> Professional
  IntimatePartner -> Public
  IntimatePartner -> Social
  IntimatePartner -> Cyber
  IntimatePartner -> NightTime
  IntimatePartner -> Intoxication
  IntimatePartner -> Singular
  IntimatePartner -> Recurring
  IntimatePartner -> Abuser
  IntimatePartner -> Supporters
  IntimatePartner -> Antagonists
  IntimatePartner -> Physical
  IntimatePartner -> Verbal
  IntimatePartner -> Economic
  IntimatePartner -> Technological
  IntimatePartner -> SexualHarassment
  IntimatePartner -> SexualAssault
  IntimatePartner -> ConfrontingAbuser
  IntimatePartner -> Reporting
  IntimatePartner -> SeveringTies
  FamilyMember -> Domestic
  FamilyMember -> Professional
  FamilyMember -> Public
  FamilyMember -> Social
  FamilyMember -> Cyber
  FamilyMember -> NightTime
  FamilyMember -> Intoxication
  FamilyMember -> Singular
  FamilyMember -> Recurring
  FamilyMember -> Abuser
  FamilyMember -> Supporters
  FamilyMember -> Antagonists
  FamilyMember -> Physical
  FamilyMember -> Verbal
  FamilyMember -> Economic
  FamilyMember -> Technological
  FamilyMember -> SexualHarassment
  FamilyMember -> SexualAssault
  FamilyMember -> ConfrontingAbuser
  FamilyMember -> Reporting
  FamilyMember -> SeveringTies
  CloseFriend -> Domestic
  CloseFriend -> Professional
  CloseFriend -> Public
  CloseFriend -> Social
  CloseFriend -> Cyber
  CloseFriend -> NightTime
  CloseFriend -> Intoxication
  CloseFriend -> Singular
  CloseFriend -> Recurring
  CloseFriend -> Abuser
  CloseFriend -> Supporters
  CloseFriend -> Antagonists
  CloseFriend -> Physical
  CloseFriend -> Verbal
  CloseFriend -> Economic
  CloseFriend -> Technological
  CloseFriend -> SexualHarassment
  CloseFriend -> SexualAssault
  CloseFriend -> ConfrontingAbuser
  CloseFriend -> Reporting
  CloseFriend -> SeveringTies
  Colleague -> Domestic
  Colleague -> Professional
  Colleague -> Public
  Colleague -> Social
  Colleague -> Cyber
  Colleague -> NightTime
  Colleague -> Intoxication
  Colleague -> Singular
  Colleague -> Recurring
  Colleague -> Abuser
  Colleague -> Supporters
  Colleague -> Antagonists
  Colleague -> Physical
  Colleague -> Verbal
  Colleague -> Economic
  Colleague -> Technological
  Colleague -> SexualHarassment
  Colleague -> SexualAssault
  Colleague -> ConfrontingAbuser
  Colleague -> Reporting
  Colleague -> SeveringTies
  AuthorityFigure -> Domestic
  AuthorityFigure -> Professional
  AuthorityFigure -> Public
  AuthorityFigure -> Social
  AuthorityFigure -> Cyber
  AuthorityFigure -> NightTime
  AuthorityFigure -> Intoxication
  AuthorityFigure -> Singular
  AuthorityFigure -> Recurring
  AuthorityFigure -> Abuser
  AuthorityFigure -> Supporters
  AuthorityFigure -> Antagonists
  AuthorityFigure -> Physical
  AuthorityFigure -> Verbal
  AuthorityFigure -> Economic
  AuthorityFigure -> Technological
  AuthorityFigure -> SexualHarassment
  AuthorityFigure -> SexualAssault
  AuthorityFigure -> ConfrontingAbuser
  AuthorityFigure -> Reporting
  AuthorityFigure -> SeveringTies
  Stranger -> Domestic
  Stranger -> Professional
  Stranger -> Public
  Stranger -> Social
  Stranger -> Cyber
  Stranger -> NightTime
  Stranger -> Intoxication
  Stranger -> Singular
  Stranger -> Recurring
  Stranger -> Abuser
  Stranger -> Supporters
  Stranger -> Antagonists
  Stranger -> Physical
  Stranger -> Verbal
  Stranger -> Economic
  Stranger -> Technological
  Stranger -> SexualHarassment
  Stranger -> SexualAssault
  Stranger -> ConfrontingAbuser
  Stranger -> Reporting
  Stranger -> SeveringTies
  Domestic -> NightTime
  Domestic -> Intoxication
  Domestic -> Supporters
  Domestic -> Antagonists
  Domestic -> Physical
  Domestic -> Verbal
  Domestic -> Economic
  Domestic -> Technological
  Domestic -> SexualHarassment
  Domestic -> SexualAssault
  Professional -> NightTime
  Professional -> Intoxication
  Professional -> Supporters
  Professional -> Antagonists
  Professional -> Physical
  Professional -> Verbal
  Professional -> Economic
  Professional -> Technological
  Professional -> SexualHarassment
  Professional -> SexualAssault
  Public -> NightTime
  Public -> Intoxication
  Public -> Supporters
  Public -> Antagonists
  Public -> Physical
  Public -> Verbal
  Public -> Economic
  Public -> Technological
  Public -> SexualHarassment
  Public -> SexualAssault
  Social -> NightTime
  Social -> Intoxication
  Social -> Supporters
  Social -> Antagonists
  Social -> Physical
  Social -> Verbal
  Social -> Economic
  Social -> Technological
  Social -> SexualHarassment
  Social -> SexualAssault
  Cyber -> NightTime
  Cyber -> Intoxication
  Cyber -> Supporters
  Cyber -> Antagonists
  Cyber -> Physical
  Cyber -> Verbal
  Cyber -> Economic
  Cyber -> Technological
  Cyber -> SexualHarassment
  Cyber -> SexualAssault
  NightTime -> Supporters
  NightTime -> Antagonists
  NightTime -> Physical
  NightTime -> Verbal
  NightTime -> Economic
  NightTime -> Technological
  NightTime -> SexualHarassment
  NightTime -> SexualAssault
  Intoxication -> Supporters
  Intoxication -> Antagonists
  Intoxication -> Physical
  Intoxication -> Verbal
  Intoxication -> Economic
  Intoxication -> Technological
  Intoxication -> SexualHarassment
  Intoxication -> SexualAssault
  Singular -> Supporters
  Singular -> Antagonists
  Singular -> Nightmares
  Singular -> Injury
  Singular -> FinancialInstability
  Singular -> LegalBarriers
  Singular -> SelfHarming
  Recurring -> Supporters
  Recurring -> Antagonists
  Recurring -> Nightmares
  Recurring -> Injury
  Recurring -> FinancialInstability
  Recurring -> LegalBarriers
  Recurring -> SelfHarming
  NotEndingAbuse -> SeekingLegalClassification
  NotEndingAbuse -> SeekingLegalAdvice
  NotEndingAbuse -> SeekingGeneralSupport
  EnablingAbuser -> SeekingLegalClassification
  EnablingAbuser -> SeekingLegalAdvice
  EnablingAbuser -> SeekingGeneralSupport
  Supporters -> NotEndingAbuse
  Supporters -> EnablingAbuser
  Supporters -> Nightmares
  Supporters -> Injury
  Supporters -> FinancialInstability
  Supporters -> LegalBarriers
  Supporters -> SelfHarming
  Antagonists -> NotEndingAbuse
  Antagonists -> EnablingAbuser
  Antagonists -> Nightmares
  Antagonists -> Injury
  Antagonists -> FinancialInstability
  Antagonists -> LegalBarriers
  Antagonists -> SelfHarming
  Physical -> NotEndingAbuse
  Physical -> EnablingAbuser
  Physical -> ConfrontingAbuser
  Physical -> Reporting
  Physical -> SeveringTies
  Physical -> SeekingLegalClassification
  Physical -> SeekingLegalAdvice
  Physical -> SeekingGeneralSupport
  Physical -> Nightmares
  Physical -> Injury
  Physical -> FinancialInstability
  Physical -> LegalBarriers
  Physical -> SelfHarming
  Verbal -> NotEndingAbuse
  Verbal -> EnablingAbuser
  Verbal -> ConfrontingAbuser
  Verbal -> Reporting
  Verbal -> SeveringTies
  Verbal -> SeekingLegalClassification
  Verbal -> SeekingLegalAdvice
  Verbal -> SeekingGeneralSupport
  Verbal -> Nightmares
  Verbal -> Injury
  Verbal -> FinancialInstability
  Verbal -> LegalBarriers
  Verbal -> SelfHarming
  Economic -> NotEndingAbuse
  Economic -> EnablingAbuser
  Economic -> ConfrontingAbuser
  Economic -> Reporting
  Economic -> SeveringTies
  Economic -> SeekingLegalClassification
  Economic -> SeekingLegalAdvice
  Economic -> SeekingGeneralSupport
  Economic -> Nightmares
  Economic -> Injury
  Economic -> FinancialInstability
  Economic -> LegalBarriers
  Economic -> SelfHarming
  Technological -> NotEndingAbuse
  Technological -> EnablingAbuser
  Technological -> ConfrontingAbuser
  Technological -> Reporting
  Technological -> SeveringTies
  Technological -> SeekingLegalClassification
  Technological -> SeekingLegalAdvice
  Technological -> SeekingGeneralSupport
  Technological -> Nightmares
  Technological -> Injury
  Technological -> FinancialInstability
  Technological -> LegalBarriers
  Technological -> SelfHarming
  SexualHarassment -> NotEndingAbuse
  SexualHarassment -> EnablingAbuser
  SexualHarassment -> ConfrontingAbuser
  SexualHarassment -> Reporting
  SexualHarassment -> SeveringTies
  SexualHarassment -> SeekingLegalClassification
  SexualHarassment -> SeekingLegalAdvice
  SexualHarassment -> SeekingGeneralSupport
  SexualHarassment -> Nightmares
  SexualHarassment -> Injury
  SexualHarassment -> FinancialInstability
  SexualHarassment -> LegalBarriers
  SexualHarassment -> SelfHarming
  SexualAssault -> NotEndingAbuse
  SexualAssault -> EnablingAbuser
  SexualAssault -> ConfrontingAbuser
  SexualAssault -> Reporting
  SexualAssault -> SeveringTies
  SexualAssault -> SeekingLegalClassification
  SexualAssault -> SeekingLegalAdvice
  SexualAssault -> SeekingGeneralSupport
  SexualAssault -> Nightmares
  SexualAssault -> Injury
  SexualAssault -> FinancialInstability
  SexualAssault -> LegalBarriers
  SexualAssault -> SelfHarming
  ConfrontingAbuser -> SeekingLegalClassification
  ConfrontingAbuser -> SeekingLegalAdvice
  ConfrontingAbuser -> SeekingGeneralSupport
  Reporting -> SeekingLegalClassification
  Reporting -> SeekingLegalAdvice
  Reporting -> SeekingGeneralSupport
  SeveringTies -> SeekingLegalClassification
  SeveringTies -> SeekingLegalAdvice
  SeveringTies -> SeekingGeneralSupport
  SeekingLegalClassification -> Abuser
  SeekingLegalAdvice -> Abuser
  SeekingGeneralSupport -> Abuser
  Nightmares -> ConfrontingAbuser
  Nightmares -> Reporting
  Nightmares -> SeveringTies
  Nightmares -> SeekingLegalClassification
  Nightmares -> SeekingLegalAdvice
  Nightmares -> SeekingGeneralSupport
  Injury -> ConfrontingAbuser
  Injury -> Reporting
  Injury -> SeveringTies
  Injury -> SeekingLegalClassification
  Injury -> SeekingLegalAdvice
  Injury -> SeekingGeneralSupport
  FinancialInstability -> ConfrontingAbuser
  FinancialInstability -> Reporting
  FinancialInstability -> SeveringTies
  FinancialInstability -> SeekingLegalClassification
  FinancialInstability -> SeekingLegalAdvice
  FinancialInstability -> SeekingGeneralSupport
  LegalBarriers -> ConfrontingAbuser
  LegalBarriers -> Reporting
  LegalBarriers -> SeveringTies
  LegalBarriers -> SeekingLegalClassification
  LegalBarriers -> SeekingLegalAdvice
  LegalBarriers -> SeekingGeneralSupport
  SelfHarming -> ConfrontingAbuser
  SelfHarming -> Reporting
  SelfHarming -> SeveringTies
  SelfHarming -> SeekingLegalClassification
  SelfHarming -> SeekingLegalAdvice
  SelfHarming -> SeekingGeneralSupport
}')

#plot(mydag)

#print(isAcyclic(mydag))

```

```{r Importing data}
final_df <- read.csv("AllFeatures.csv", header = T)

final_df <- final_df %>% 
  rename("Injury" = "PhysicalInjury",
         "ConfrontingAbuser" = "Confrontabuser",
         "Intoxication" = "Intoxicated",
         "Abuser" = "DetailedAbuserDiscussion",
         "SeekingGeneralSupport" = "SeekingSupport")

final_df <- final_df %>% mutate(across(everything(), ~ ifelse(. != "Yes", "No", .)))
```


```{r causal_model_formulation}
fit_causal_model <- function(data, treatment, response, confounder) {
  
  data[[treatment]] <- as.factor(data[[treatment]])
  data[[response]] <- as.factor(data[[response]])
  
  # Full Model - Binary logistic regression
  formula <- as.formula(paste(response, '~', treatment, '+', 
        paste0(confounder, collapse = ' + '),
        '+', treatment, '*(',paste0(confounder, collapse = '+'),
        ')'))
  model <- glm(formula, data = data, family = binomial)
  
  pred1 <- predict(model, 
                   newdata = data.frame(A = "Yes", data[, confounder]) %>% setNames(c(treatment, confounder)),
                   se.fit = T, type = "response")
  
  pred0 <- predict(model, 
                   newdata = data.frame(A = "No", data[, confounder]) %>% setNames(c(treatment, confounder)),
                   se.fit = T, type = "response")
  
  oi.est <- mean(pred1$fit) - mean(pred0$fit)
  oi.sd <- sqrt(sum((pred1$se.fit^2), (pred0$se.fit^2)))/nrow(data)
  
  append_to_csv(data.frame(Cause = treatment,
                           Effect = response,
                           Value = oi.est,
                           pvalue = pnorm(abs(oi.est), sd = oi.sd, lower.tail = F) %>% round(digits = 3)) %>%
                  mutate(Significant = pvalue < 0.05))

  return(model)
}
```


```{r model1fit}
# model 1
cause_list1.1 <- c("IntimatePartner", "FamilyMember", "CloseFriend", "Colleague", "AuthorityFigure", "Stranger")
cause_list1.2 <- c("NightTime", "Intoxication", "Singular", "Recurring", "Domestic", "Professional", "Public", "Social", "Cyber")

effect_list1 <- c("Physical", "Verbal", "Economic", "Technological", "SexualHarassment", "SexualAssault", "Injury")

for (cause in cause_list1.1) {
  for (effect in effect_list1){
    cat("\n\nTesting Causal Effect of", cause, "on", effect, "\n")
    fit <- fit_causal_model(final_df, cause, effect, adjustmentSets(mydag, cause, effect, type = "canonical")[[1]])
    # print(summary(fit))
  }
}

for (cause in cause_list1.2) {
  for (effect in effect_list1){
    cat("\n\nTesting Causal Effect of", cause, "on", effect, "\n")
    fit <- fit_causal_model(final_df, cause, effect, adjustmentSets(mydag, cause, effect, type = "canonical")[[1]])
    # print(summary(fit))
  }
}
```

```{r model2fit}
# model 2
cause_list2 <- c("Physical", "Verbal", "Economic", "Technological", "SexualHarassment", "SexualAssault", "Antagonists", "Supporters", "Singular", "Recurring")
effect_list2 <- c("Nightmares", "ConfrontingAbuser", "Reporting", "SeveringTies")

for (cause in cause_list2) {
  for (effect in effect_list2){
    cat("\n\nTesting Causal Effect of", cause, "on", effect, "\n")
    fit <- fit_causal_model(final_df, cause, effect, adjustmentSets(mydag, cause, effect, type = "canonical")[[1]])
    #print(summary(fit))
  }
}
```
  
```{r model3fit}
# model 3
cause_list3 <- c("Physical", "Verbal", "Economic", "Technological", "SexualHarassment", "SexualAssault", 
                 "Antagonists", "Supporters", "Singular", "Recurring")
effect_list3 <- c("NotEndingAbuse", "EnablingAbuser")

for (cause in cause_list3) {
  for (effect in effect_list3){
    cat("\n\nTesting Causal Effect of", cause, "on", effect, "\n")
    fit <- fit_causal_model(final_df, cause, effect, adjustmentSets(mydag, cause, effect, type = "canonical")[[1]])
    #print(summary(fit))
  }
}
```


```{r model4fit}
# model 4'
cause_list4 <- c("Physical", "Verbal", "Economic", "Technological", "SexualHarassment", "SexualAssault", "IntimatePartner", "FamilyMember", "CloseFriend", "Colleague", "AuthorityFigure", "Stranger", "Singular", "Recurring", "NightTime", "Intoxication")
effect_list4 <- c("SeekingLegalClassification", "SeekingLegalAdvice", "SeekingGeneralSupport", "Abuser")

for (cause in cause_list4) {
  for (effect in effect_list4){
    cat("\n\nTesting Causal Effect of", cause, "on", effect, "\n")
    fit <- fit_causal_model(final_df, cause, effect, adjustmentSets(mydag, cause, effect, type = "canonical")[[1]])
    #print(summary(fit))
  }
}
```

```{r model5fit}
# model 5
cause_list5 <- c("Nightmares", "Injury", "FinancialInstability", "LegalBarriers", "SelfHarming", "ConfrontingAbuser", "Reporting", "SeveringTies")
effect_list5 <- c("SeekingLegalClassification", "SeekingLegalAdvice", "SeekingGeneralSupport", "Abuser")

for (cause in cause_list5) {
  for (effect in effect_list5){
    cat("\n\nTesting Causal Effect of", cause, "on", effect, "\n")
    fit <- fit_causal_model(final_df, cause, effect, adjustmentSets(mydag, cause, effect, type = "canonical")[[1]])
    #print(summary(fit))
  }
}
```